apiVersion: v1
kind: Service
metadata:
  name: explorer-app-service
  namespace: explorer-lab
  labels:
    app: explorer-app
spec:
  type: NodePort
  selector:
    app: explorer-app
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30080
      protocol: TCP
      name: http
